.\" Manpage for kermit.
.TH KERMIT "1" "Feb 2022" "kermit" "User Commands"
.SH NAME
kermit \- a VTE-based terminal emulator
.SH SYNOPSIS
.B kermit
[options]
.SH DESCRIPTION
kermit is a VTE-based, simple and froggy terminal emulator.
.SH OPTIONS
.TP
\fB\-c\fR <PATH>
set the configuration file
.TP
\fB\-t\fR <TITLE>
set the terminal title
.TP
\fB\-w\fR <DIR>
set the working directory
.TP
\fB\-e\fR <CMD>
set the command to run
.TP
\fB\-d\fR
activate debug messages
.TP
\fB\-v\fR
show version
.TP
\fB\-h\fR
show help
.SH BUGS
No known bugs.
Use "Issues" page for reporting bugs: <https://github.com/orhun/kermit/issues/>
.SH AUTHOR
Written by Orhun Parmaksız <orhunparmaksiz@gmail.com>
.SH COPYRIGHT
Copyright © 2019-2023 Orhun Parmaksız
.P
GNU General Public License v3.0 only
